<div id="dashboard">
    <div class="pull-left">
        <a href="#addTask" role="button" class="btn btn-primary" data-toggle="modal">
            <i class="icon-plus icon-white"></i>
            Add Task
        </a>
    </div>
    <div class="pull-right">
        <a href="#addTask" role="button" class="btn btn-warning" data-toggle="modal">
            <i class="icon-calendar icon-white"></i>
            Show Calendar</a>
    </div>
    <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="example">
        <caption><h4>Recent Tasks</h4></caption>
        <thead>
            <tr>
                <th>Rendering engine</th>
                <th>Browser</th>
                <th>Platform(s)</th>
                <th>Engine version</th>
                <th>CSS grade</th>
            </tr>
        </thead>
        <tbody>
            <tr class="odd gradeX">
                <td>Trident</td>
                <td>Internet
                    Explorer 4.0</td>
                <td>Win 95+</td>
                <td class="center"> 4</td>
                <td class="center">X</td>
            </tr>
            <tr class="even gradeA">
                <td>Trident</td>
                <td>AOL browser (AOL desktop)</td>
                <td>Win XP</td>
                <td class="center">6</td>
                <td class="center">A</td>
            </tr>
            <tr class="gradeA">
                <td>Gecko</td>
                <td>Firefox 1.0</td>
                <td>Win 98+ / OSX.2+</td>
                <td class="center">1.7</td>
                <td class="center">A</td>
            </tr>
            <tr class="gradeA">
                <td>Gecko</td>
                <td>Firefox 1.5</td>
                <td>Win 98+ / OSX.2+</td>
                <td class="center">1.8</td>
                <td class="center">A</td>
            </tr>
            <tr class="gradeA">
                <td>Gecko</td>
                <td>Firefox 2.0</td>
                <td>Win 98+ / OSX.2+</td>
                <td class="center">1.8</td>
                <td class="center">A</td>
            </tr>
        </tbody>
    </table>
    <div class="clearfix"></div>
</div>
<hr/>
<div>
    <div class="pull-left">
        <a href="#addTask" role="button" class="btn btn-primary" data-toggle="modal">
            <i class="icon-plus icon-white"></i>
            Add Room Schedule
        </a>
    </div>
    <div class="pull-right">
        <a href="#addTask" role="button" class="btn btn-warning" data-toggle="modal">
            <i class="icon-calendar icon-white"></i>
            Show Calendar
        </a>
    </div>
    <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="example">
        <caption><h4>Recent Room Schedules</h4></caption>
        <thead>
            <tr>
                <th>Room</th>
                <th>Schedule</th>
                <th>Schedule</th>
                <th>Reserved By</th>
            </tr>
        </thead>
        <tbody>
            <tr class="odd gradeX">
                <td>Trident</td>
                <td>Internet
                    Explorer 4.0
                </td>
                <td>Win 95+</td>
                <td class="center"> 4</td>
            </tr>
            <tr class="even gradeA">
                <td>Trident</td>
                <td>AOL browser (AOL desktop)</td>
                <td>Win XP</td>
                <td class="center">6</td>
            </tr>
            <tr class="gradeA">
                <td>Gecko</td>
                <td>Firefox 1.0</td>
                <td>Win 98+ / OSX.2+</td>
                <td class="center">1.7</td>
            </tr>
            <tr class="gradeA">
                <td>Gecko</td>
                <td>Firefox 1.5</td>
                <td>Win 98+ / OSX.2+</td>
                <td class="center">1.8</td>
            </tr>
            <tr class="gradeA">
                <td>Gecko</td>
                <td>Firefox 2.0</td>
                <td>Win 98+ / OSX.2+</td>
                <td class="center">1.8</td>
            </tr>
        </tbody>
    </table>
</div>




<!-- Modal -->
<div class="modal hide fade " style="display:none" id="addTask" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div>
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3 id="myModalLabel">Test</h3>
        </div>
        <div class="modal-body">
            <form class="form-horizontal">
                <div class="control-group">
                    <label class="control-label" for="inputOwner">Owner</label>
                    <div class="controls">
                        <input type="text" id="inputOwner" placeholder="Owner"/>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="inputActivityTitle">Activity Title</label>
                    <div class="controls">
                        <input type="text" id="inputActivityTitle" placeholder="Activity Title">
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="inputActivityTitle">Activity Description</label>
                    <div class="controls">
                        <textarea  rows="5" placeholder="Activity Description"></textarea>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="inputActivityTitle">Location</label>
                    <div class="controls">
                        <input type="text" placeholder="Location"/>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="inputActivityTitle">Start Date</label>
                    <div class="controls">
                        <input type="text" placeholder="Start Date" />
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="inputActivityTitle">Due Date</label>
                    <div class="controls">
                        <input type="text" placeholder="Due Date" />
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="inputActivityTitle">Remarks</label>
                    <div class="controls">
                        <textarea  rows="5" placeholder="Remarks"></textarea>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="inputActivityTitle">Status</label>
                    <div class="controls">
                        <select>
                            <option>Open</option>
                            <option>Closed</option>
                        </select>
                    </div>
                </div>
            </form>
        </div>
        <div class="modal-footer">
            <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
            <button class="btn btn-primary">Save changes</button>
        </div>
    </div>
</div>
