<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Task Management System</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">

        <!-- Le styles -->
        <link href="<?php echo $this->baseUrl(); ?>/assets/framework/tb/assets/css/bootstrap.css" rel="stylesheet" />
        <link href="<?php echo $this->baseUrl(); ?>/assets/css/style.css" rel="stylesheet" />
        <style type="text/css">
            body {
                padding-top: 60px;
                padding-bottom: 40px;
            }
            .sidebar-nav {
                padding: 9px 0;
            }
        </style>
        <link href="<?php echo $this->baseUrl(); ?>/assets/framework/tb/assets/css/bootstrap-responsive.css" rel="stylesheet">

        <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
          <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->

        <!-- Le fav and touch icons -->
        <link rel="shortcut icon" href="<?php echo $this->baseUrl(); ?>/assets/framework/tb/assets/ico/favicon.ico">
        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="<?php echo $this->baseUrl(); ?>/assets/framework/tb/assets/ico/apple-touch-icon-144-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="<?php echo $this->baseUrl(); ?>/assets/framework/tb/assets/ico/apple-touch-icon-114-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="<?php echo $this->baseUrl(); ?>/assets/framework/tb/assets/ico/apple-touch-icon-72-precomposed.png">
        <link rel="apple-touch-icon-precomposed" href="<?php echo $this->baseUrl(); ?>/assets/framework/tb/assets/ico/apple-touch-icon-57-precomposed.png">

    </head>

    <body data-spy="scroll">
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container-fluid">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <div class="span3">
                        <a class="brand" href="/">Task Management System</a>
                    </div>
                    <div class="nav-collapse collapse">
                        <p class="navbar-text pull-right">

                        </p>
                    </div>
                </div>
            </div>
        </div>

        <div class="container-fluid">
            <div class="row-fluid">
                <div id="navbar" class="span3">
                    <div class=" well sidebar-nav ">
                        <ul class="nav nav-list affix-top">
                            <li class="nav-header">Navigation</li>
                            <li class="<?php echo ($this->dashboard) ? "active" : "" ?>"><a href="<?php echo $this->baseUrl(); ?>/dashboard">Dashboard</a></li>
                            <li class="<?php echo ($this->activities) ? "active" : ""; ?>" ><a href="<?php echo $this->baseUrl(); ?>/activities">Activities</a></li>
                            <li class="<?php echo ($this->roomSchedule) ? "active" : ""; ?>" ><a href="<?php echo $this->baseUrl(); ?>/room-schedules">Room Schedules</a></li>
                            <li class="nav-header">Logged in as Arjay</li>
                            <li ><a href="#">Profile</a></li>
                            <li ><a href="#">Logout</a></li>
                        </ul>
                    </div><!--/.well -->
                </div><!--/span-->
                <div id="content" class="span9">
                    <div id="calendar" class="pages" data-url="/ajax/public/index/calendar"></div>

                    <div id="main-content">
                        <fieldset>
                            <legend><?php echo $this->pageTitle ?></legend>
                            <?php echo $this->layout()->content; ?>
                        </fieldset>
                    </div>


                </div><!--/span-->
            </div><!--/row-->

            <hr>

            <footer>
                <p class="center" style="text-align:center">&copy; Company 2012</p>
            </footer>

        </div><!--/.fluid-container-->

        <!-- Le javascript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="<?php echo $this->baseUrl(); ?>/assets/framework/tb/assets/js/jquery.js"></script>
        <script src="<?php echo $this->baseUrl(); ?>/assets/framework/tb/assets/js/bootstrap-transition.js"></script>
        <script src="<?php echo $this->baseUrl(); ?>/assets/framework/tb/assets/js/bootstrap-alert.js"></script>
        <script src="<?php echo $this->baseUrl(); ?>/assets/framework/tb/assets/js/bootstrap-modal.js"></script>
        <script src="<?php echo $this->baseUrl(); ?>/assets/framework/tb/assets/js/bootstrap-dropdown.js"></script>
        <script src="<?php echo $this->baseUrl(); ?>/assets/framework/tb/assets/js/bootstrap-scrollspy.js"></script>
        <script src="<?php echo $this->baseUrl(); ?>/assets/framework/tb/assets/js/bootstrap-tab.js"></script>
        <script src="<?php echo $this->baseUrl(); ?>/assets/framework/tb/assets/js/bootstrap-tooltip.js"></script>
        <script src="<?php echo $this->baseUrl(); ?>/assets/framework/tb/assets/js/bootstrap-popover.js"></script>
        <script src="<?php echo $this->baseUrl(); ?>/assets/framework/tb/assets/js/bootstrap-button.js"></script>
        <script src="<?php echo $this->baseUrl(); ?>/assets/framework/tb/assets/js/bootstrap-collapse.js"></script>
        <script src="<?php echo $this->baseUrl(); ?>/assets/framework/tb/assets/js/bootstrap-carousel.js"></script>
        <script src="<?php echo $this->baseUrl(); ?>/assets/framework/tb/assets/js/bootstrap-typeahead.js"></script>
        <script src="<?php echo $this->baseUrl(); ?>/assets/framework/tb/assets/js/bootstrap-affix.js"></script>
        <!--Le Full calendar -->
        <link rel='stylesheet' type='text/css' href='<?php echo $this->baseUrl(); ?>/assets/js/plugins/fullcalendar-1.5.3/fullcalendar/fullcalendar.css' />
        <link rel='stylesheet' type='text/css' href='<?php echo $this->baseUrl(); ?>/assets/js/plugins/fullcalendar-1.5.3/fullcalendar/fullcalendar.print.css' media='print' />
        <script type='text/javascript' src='<?php echo $this->baseUrl(); ?>/assets/js/plugins/fullcalendar-1.5.3/fullcalendar/fullcalendar.min.js'></script>
        <!-- Le Datatables-->
        <script type="text/javascript" language="javascript" src="http://datatables.net/release-datatables/media/js/jquery.dataTables.js"></script>
        <link rel='stylesheet' type='text/css' href='<?php echo $this->baseUrl(); ?>/assets/js/plugins/fullcalendar-1.5.3/fullcalendar/fullcalendar.print.css' media='print' />
        <style>
            div.dataTables_length label {
                width: 460px;
                float: left;
                text-align: left;
            }

            div.dataTables_length select {
                width: 75px;
            }

            div.dataTables_filter label {
                float: right;
                width: 460px;
            }

            div.dataTables_info {
                padding-top: 8px;
            }

            div.dataTables_paginate {
                float: right;
                margin: 0;
            }

            table {
                margin: 1em 0;
                clear: both;
            }
        </style>
        <!--Datatables Styles-->
        <script>
         
        </script>
        <script src="<?php echo $this->baseUrl(); ?>/assets/js/app/app.js"></script>
        <script src="<?php echo $this->baseUrl(); ?>/assets/js/app/functions.js"></script>
        <script src="<?php echo $this->baseUrl(); ?>/assets/js/app/transitions.js"></script>
        <script>
            $(".task").dblclick(function(){
                var task = $(this);
                if(task.children(".task-list-info").hasClass("hidden")){
                    task.children(".task-list-info").removeClass("hidden").addClass("shown").hide("fast").slideDown();
                }else{
                    task.children(".task-list-info").slideUp("fast").addClass("hidden")
                }

            });
        </script>
    </body>
</html>
