<style>
    .owner{font-size:smaller;padding:5px;text-shadow: 0px 1px 0px white}
    .task{margin:5px 0;padding:5px 10px;border-radius:3px;cursor: pointer}
    .task:nth-child(odd){background: #ddd}
    .task:hover{background: #eee}
    .task-info{display:none}
    .task-title{display:inline}
    .task-list-info{display:none;;padding-left: 35px;}
    .task-list-info.shown{display:block;}
    .task-list-info.hidden{display:none;}
</style>


<div class="row-fluid">
    <div class="span12">
        <div class="task">
            <div class="task-list-item">
                <button class="btn btn-inverse"></button> 
                <div class="task-title">
                    This is a sample Activity Title
                </div>
                <div class="owner pull-right">
                    Owned by : Arjay A. Macabia
                </div>
            </div>
            <div class="task-list-info hidden">
                This is a very very long task list info
            </div>
        </div>

        <div class="task">
            <button class="btn btn-success"></button> 
            This is a sample Activity Title
            <div class="owner pull-right">
                Owned by : Arjay A. Macabia
            </div>
        </div>
        <div class="task">
            <button class="btn btn-success"></button> 
            This is a sample Activity Title
            <div class="owner pull-right">
                Owned by : Arjay A. Macabia
            </div>
        </div>
        <div class="task">
            <button class="btn btn-success"></button> 
            This is a sample Activity Title
            <div class="owner pull-right">
                Owned by : Arjay A. Macabia
            </div>
        </div>
        <div class="task">
            <button class="btn btn-success"></button> 
            This is a sample Activity Title
            <div class="owner pull-right">
                Owned by : Arjay A. Macabia
            </div>
        </div>
        <div class="task">
            <button class="btn btn-danger"></button> 
            This is a sample Activity Title
            <div class="owner pull-right">
                Owned by : Arjay A. Macabia
            </div>
        </div>
        <div class="task">
            <button class="btn btn-success"></button> 
            This is a sample Activity Title
            <div class="owner pull-right">
                Owned by : Arjay A. Macabia
            </div>
        </div>
    </div>

</div>